service: assessorscraper
app: assessor-scraper
# Plugins for the project
plugins:
  - serverless-offline-sqs
  - serverless-offline-scheduler
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  saveTowns:
    handler: handlers/saveTowns/handler.saveTowns
    events:
      - schedule: rate(1 minute)

custom:
  custom:
    serverless-offline:
      host: 0.0.0.0
  serverless-offline-sqs:
    autoCreate: true                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

